export const subjects = [
  "maths",
  "language",
  "science",
  "history",
  "coding",
  "economics",
  "geography",
  "physics",
  "chemistry",
  "biology",
  "computer science",
  "english",
  "hindi",
  "political science",
  "sociology",
  "psychology",
  "philosophy",
  "business studies",
  "accountancy",
  "environmental science",
  "art",
  "music",
  "physical education",
  "robotics",
  "data science",
  "ai",
  "machine learning",
  "entrepreneurship"
];

export const subjectsColors = {
  maths: "#FFDA6E",
  language: "#BDE7FF",
  science: "#E5D0FF",
  history: "#FFECC8",
  coding: "#FFC8E4",
  economics: "#C8FFDF",
  geography: "#FCE2CE",
  physics: "#D0F0FD",
  chemistry: "#FFE3E3",
  biology: "#C7F9E9",
  computer: "#DAD0FF",
  "computer science": "#DAD0FF",
  english: "#FFEBB7",
  hindi: "#FFE4CC",
  "political science": "#E0FFE1",
  sociology: "#F2DAFF",
  psychology: "#FFD3F3",
  philosophy: "#D0F0C0",
  "business studies": "#FFF0D0",
  accountancy: "#D7ECFF",
  "environmental science": "#C6FFD7",
  art: "#F9D0FF",
  music: "#E0D4FD",
  "physical education": "#C8FFD4",
  robotics: "#F5E0FF",
  "data science": "#C5F1FF",
  ai: "#FFD9E6",
  "machine learning": "#FFDFC8",
  entrepreneurship: "#FFF0C8"
};

export const voices = {
  male: { casual: "2BJW5coyhAzSr8STdHbE", formal: "c6SfcYrb2t09NHXiT80T" },
  female: { casual: "ZIlrSGI4jZqobxRKprJz", formal: "sarah" },
};
